### ISSUE TITLE
記事が読みにくいかもしれない

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-landing-page#24]
アニメーションの影響で記事が少し読みにくい気がします、
アニメーションを無効にするか、もう少しスピードを速くするか、アニメーション部分を少なくする（左右から出てくる記事をもう少し多くする）等で解決できると思います

**Comment by KanadeNishizawa** [comment]
確認遅れてすみません、修正案ありがとうございます！
見づらくなってるアニメーション、前半の横から出てくる部分ですかね・・・？
他の部分も含めてでしょうか？

**Comment by takonasu** [comment]
確認遅れましたすいません・・・
前半の横から出てくる部分が特に目立って、あとは全体的にちょっとレスポンスが遅い（？）気がします・・・
スクロールしてから記事が出てくるのに時間がかかってしまうので、ちょっときになるかなと思った次第です。
