### ISSUE TITLE
広告用写真の追加

### ISSUE THREAD

**Issue by HikaruEgashira** [twin-te/twinte-landing-page#7]
## 概要

アプリストアに掲載するためのスクリーンショット画像などを制作する。
一応www直下にアーカイブしときたい（いろいろ企画紹介とかに使えるかも?）
KanadeとHikaruで行う予定

## 要件

- ?(play storeとapp storeの規格に合うようなデザイン)
@takonasu @SIY1121 サイズ等を教えて

## 優先度

3

**Comment by SIY1121** [comment]
Play Store です🙏
![image](https://user-images.githubusercontent.com/17082836/70031861-96d30400-15ef-11ea-8fbb-fac698869ef2.png)
