### ISSUE TITLE
お問合せチャットを消す

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-landing-page#82]
お問合せチャットがあまり使われていない＆運営にSlackを持ちいらなくなったためお問合せチャットを消す

**Comment by HosokawaR** [comment]
言及し忘れていたのですが https://github.com/twin-te/twinte-landing-page/pull/84/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L31 にてすでに Small Chat は削除されているのでこの Issue は閉じます。
