### ISSUE TITLE
`/public` が公開されない

### ISSUE THREAD

**Issue by HosokawaR** [twin-te/twinte-landing-page#87]
## 背景

OGP 画像や Favicon などが表示されない
調べてみると `/public` 以下が公開されていない

https://github.com/nuxt/nuxt/issues/12876 とかがあやしい

## 解決策

パッケージアップデート
原因の特定もしたい

**Comment by takonasu** [comment]
手元で最新のNuxにアップデートしてみても解決しなかったです・・・

**Comment by HosokawaR** [comment]
すみません…ただ単に僕が Default の設定を変えたから、public がコピーされなかったのです…
https://github.com/twin-te/twinte-landing-page/pull/88
