### ISSUE TITLE
メンバー更新

### ISSUE THREAD

**Issue by HosokawaR** [twin-te/twinte-landing-page#99]
- 新メンバーを追加
  - 追加メンバーのプロフィールは [Twin:te Discord](https://discord.com/channels/1008574300787322980/1008578693679026309/1274319824750772286) 参照
- OB は OB 欄に移動させていただく
  - たこなす, SIY1121, あざらしさん
  - 「その他のメンバー」 → 「OB・OG」

**Comment by s7tya** [comment]
#101  で close
